### ISSUE TITLE
Fatal IDE error

### ISSUE THREAD

**Issue by mgray88** [bealex/SwiftLintAppCode#43]
Getting the following exception with the latest versions:
swiftlint 0.34.0
SwiftLintAppCode 1.10.5
AppCode 2019.2

```
ExternalToolPass: 

com.intellij.diagnostic.PluginException: annotator: com.lonelybytes.swiftlint.annotator.SwiftLintHighlightingAnnotator@37ecaa9a (class com.lonelybytes.swiftlint.annotator.SwiftLintHighlightingAnnotator) [Plugin: com.appcodeplugins.swiftlint]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:403)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:69)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.process(ExternalToolPass.java:253)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doApply(ExternalToolPass.java:219)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:39)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$null$0(ExternalToolPass.java:183)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:936)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:180)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$11(BackgroundTaskUtil.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:264)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:243)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:178)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:324)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:314)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:264)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:278)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:233)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'textRange' of com/intellij/codeInsight/daemon/impl/HighlightInfo$B.range must not be null
	at com.intellij.codeInsight.daemon.impl.HighlightInfo$B.$$$reportNull$$$0(HighlightInfo.java)
	at com.intellij.codeInsight.daemon.impl.HighlightInfo$B.range(HighlightInfo.java)
	at com.lonelybytes.swiftlint.annotator.SwiftLintHighlightingAnnotator.processErrorLine(SwiftLintHighlightingAnnotator.java:413)
	at com.lonelybytes.swiftlint.annotator.SwiftLintHighlightingAnnotator.highlightInfos(SwiftLintHighlightingAnnotator.java:164)
	at com.lonelybytes.swiftlint.annotator.SwiftLintHighlightingAnnotator.apply(SwiftLintHighlightingAnnotator.java:172)
	at com.lonelybytes.swiftlint.annotator.SwiftLintHighlightingAnnotator.apply(SwiftLintHighlightingAnnotator.java:48)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doApply(ExternalToolPass.java:216)
	... 37 more
```

**Comment by bealex** [comment]
Hi, thanks for the report. 

Is it possible to see the code that triggers that?

**Comment by mgray88** [comment]
Can't post exact code so I'm trying to create a test project that recreates it. It seems there are two issues I'm facing. Simply having a `.swiftlint.yml` file cause the plugin to fail to run period, even if it's empty.

This is the simplest code I was able to recreate the error with:

```
import Foundation

protocol AutoCodable: Codable {
    static var decoder: JSONDecoder { get }
}

extension AutoCodable {
    static var decoder: JSONDecoder {
        return JSONDecoder()
    }
}

class MenuItem: AutoCodable {
}

@objc
class Test : NSObject {

    static func loadFixture<T: AutoCodable>(fixture: String) -> T {
        let bundle = Bundle(for: Test.self)
        let resource = bundle.url(forResource: fixture, withExtension: "json")!
        let data = try! Data(contentsOf: resource)

        return try! T.decoder.decode(T.self, from: data)
    }

    static func MenuItem() -> MenuItem {
        return loadFixture(fixture: "MenuItem")
    }
}
```

It's the `static func MenuItem()` function that causes the issue. Comment it out and the linter works fine.

**Comment by bealex** [comment]
Thanks a lot! Can you please tell the structure of the project? Maybe you have several `.swiftlint.yml` files there?

**Comment by mgray88** [comment]
AppCode -> New Project -> Single view iOS App

**Comment by bealex** [comment]
Got it!

**Comment by mgray88** [comment]
[Test.zip](https://github.com/bealex/SwiftLintAppCode/files/3442610/Test.zip)

**Comment by bealex** [comment]
Got it! Should be fixed in next update (1.10.6). Please tell if something is still wrong.

**Comment by mgray88** [comment]
I'll check it in Monday. Thanks for your work!

**Comment by bealex** [comment]
It'll be available when JB will review it. It can take a couple of days.

**Comment by mgray88** [comment]
Gotcha
